//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NishClub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NishClubDBEntities : DbContext
    {
        public NishClubDBEntities()
            : base("name=NishClubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Members> tbl_Members { get; set; }
        public virtual DbSet<tbl_OrderBaskets> tbl_OrderBaskets { get; set; }
        public virtual DbSet<tbl_Orders> tbl_Orders { get; set; }
    }
}
