//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NishClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Members
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public string Password { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public string CardNo { get; set; }
    }
}
